config/routes.rb
unless RakeSettings.self_skip_initializers?
  Rails.application.routes.draw do
    mount Ckeditor::Engine => '/ckeditor'
    devise_for :users
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

    resources :line_items
    resources :carts

    delete '/line_items/:id' => 'line_items#destroy'
    post '/customized_form' => 'main#customized_form'
    post '/call_order' => 'main#call_order'
    post '/contact_form' => 'main#contact_form'
    post '/order_product' => 'main#order_product'

    scope "(:locale)", :locale => /uk|en/ do
      get '/contacts' => 'main#contacts', as: 'contacts'

      get '/publication' => 'main#all_publication', as: 'all_publication'
      get '/publication/:url' => 'main#one_article', as: "one_article"

      get '/tablecloth' => 'product#all_tablecloth', as: 'all_tablecloth'
      get '/tablecloth/:category' => 'product#one_item', as: 'one_product'
      get '/tablecloth/:category/:name' => 'product#product_detail', as: 'product_detail'

      get '/sets' => 'product#all_sets', as: 'all_sets'
      get '/sets/:category' => 'product#sets_category', as: 'sets_category'
      get '/sets/:category/:name' => 'product#drink_set_detail', as: 'sets_detail'

      get '/decors' => 'product#all_decors', as: 'all_decors'
      get '/decors/:name' => 'product#decor_detail', as: 'decors_detail'

      get '/special_offers' => 'main#special_offers', as: 'special_offers'

      get '/delivery' => 'info#shipping', as: 'shipping'
      get '/warranty' => 'info#warranty', as: 'warranty'
      get '/payment' => 'info#payment', as: 'payment'

      get '/ordering' => 'main#ordering', as: 'ordering'

      root "main#index"

    end
    post '/add_products_pack' => 'line_items#add_product_pack_item_to_line_item', as: 'add_product_pack_item_to_line_item'
    match "*path" => redirect("/"), via: [:get, :post]
  end

end

app/views/partials/_footer.html.slim
footer.sf_footer
  .footer_wrap
    .f_menu_wrap
      .row
        .columns.large-12
          ul.f_menu
            li
              - subcategory = Category.where(:parent_id => true).first
              =link_to t("main_menu.tablecloths"), one_product_path(subcategory.category_url, locale: I18n.locale)
                /=t("main_menu.tablecloths")
            /li
            /  - ds_category = DsCategory.where(:parent_id => nil).first
            /  =link_to sets_category_path(ds_category.t_name, locale: I18n.locale) do
            /    |Сервізи
            /li
              - d_category = DCategory.order('created_at DESC').first
              =link_to t("main_menu.decors"), decor_category_path(d_category.t_name, locale: I18n.locale)
            li
              =link_to t("main_menu.decors"), all_decors_path(locale: I18n.locale)
                /| Декори
            li
              =link_to t("main_menu.promotion"), special_offers_path(locale: I18n.locale)
            li
              =link_to t("main_menu.publications"), all_publication_path(locale: I18n.locale)
            li
              =link_to t("main_menu.delivery"), shipping_path(locale: I18n.locale)
            li
              =link_to t("main_menu.guarantee"), warranty_path(locale: I18n.locale)
            li
              =link_to t("main_menu.payment"), payment_path(locale: I18n.locale)
            li
              =link_to t("main_menu.contacts"), contacts_path(locale: I18n.locale)
    .f_navigation_wrap
      .f_links_wrap
        .row
          .columns.large-4
            .row.dn.mdb
              .columns.small-12
                ul.social_networks_wrap
                  li
                    a href="tell:+380504170728"
                      = embedded_svg ("MO-Phone.svg"), class: "f_ico"
                  li
                    a href="mailto:voronin.nick@gmail.com"
                      = embedded_svg ("MO-Mail.svg"), class: "f_ico"
                  li
                    a href="https://www.facebook.com/" rel="nofollow"
                      = embedded_svg ('MO-Social-Facebook.svg'), class: "f_ico"
                  li
                    a href="http://instagram.com/" rel="nofollow"
                      = embedded_svg ('MO-Social-Instagram.svg'), class: "f_ico"
                  li
                    a href="https://twitter.com/" rel="nofollow"
                      = embedded_svg ('MO-Social-Twitter.svg'), class: "f_ico"
            .row.mdn
              .columns.large-12
                a href="tell:+380671070727"
                  .link_inner.link_phone_inner.phone-link-with-brackets
                    = embedded_svg ("MO-Phone.svg"), class: "f_ico"
                    span
                      |+38&nbsp;
                      .bracket
                        |(
                      |067
                      .bracket
                        |)
                      |&nbsp;107 07 27
            .row.mdn
              .columns.large-12
                a href="mailto:magia-obrus@ukr.net"
                  .link_inner.link_mail_inner
                    = embedded_svg ("MO-Mail.svg"), class: "f_ico"
                    span
                      |magia-obrus@ukr.net
          .columns.large-5.small-12
            = render partial: "partials/forms/mail_chimp_subs_form"

          .columns.large-3.mdn
            ul.social_networks_wrap
              li
                a href="https://www.facebook.com/" rel="nofollow"
                  = embedded_svg ('MO-Social-Facebook.svg'), class: "f_ico"
              li
                a href="http://instagram.com/" rel="nofollow"
                  = embedded_svg ('MO-Social-Instagram.svg'), class: "f_ico"
              li
                a href="https://twitter.com/" rel="nofollow"
                  = embedded_svg ('MO-Social-Twitter.svg'), class: "f_ico"
      .f_about_wrap
        .row
          .columns.large-5
            p.faw_left =t("pages.footer.project_sponsor")
          .columns.large-4
            ul.voronin-block-wrap
              li.vbw-image
                a href="http://voroninstudio.eu/" rel="nofollow"
                  svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="52px" height="55px" viewBox="0 0 52 55" enable-background="new 0 0 52 55" xml:space="preserve"
                    g
                      g
                        path fill="#CBCBCB" d="M33.146,33.782c-0.068,0.039-0.126,0.073-0.176,0.103c3.201,1.559,8.311,3.211,13.26,3.329c1.355-2.407,2.599-4.907,3.449-7.581c-4.572,1.977-9.493,2.792-14.729,3.04C34.358,33.058,33.757,33.427,33.146,33.782z"
                        path fill="#CBCBCB" d="M37.849,30.602c4.668-0.753,9.847-2.614,12.758-4.483c0.736-3.134,1.131-6.399,1.131-9.758c0-1.411-0.07-2.806-0.205-4.182C48.729,19.514,43.95,25.866,37.849,30.602z"
                        path fill="#CBCBCB" d="M45.348,38.45c-5.48,0-10.719-1.038-15.529-2.928c-2.884-1.132-5.612-2.57-8.149-4.275c-0.021-0.015-0.044-0.028-0.065-0.043C11.376,24.302,4.314,13.066,3.052,0.131c-1.8,4.71-2.789,9.821-2.789,15.165c0,0.745,0.02,1.486,0.057,2.222c0.027,0.521,0.066,1.037,0.112,1.554c0.147,1.675,0.374,3.368,0.729,5.023c0.105,0.488,0.055,0.303,0.105,0.488c2.988,3.141,9.128,7.002,10.672,8.105c-1.575-0.314-7.415-3.135-9.733-4.668c1.332,4.25,3.327,8.459,6.011,12.029c1.926,0.816,5.661,2.653,6.985,3.102c-1.703-0.165-4.077-0.846-5.617-1.299c4.439,5.539,10.235,9.943,16.885,12.706c0.255,0.105,0.51,0.211,0.767,0.312c1.246-0.584,2.459-1.226,3.636-1.923c6.002-3.557,11.055-8.546,14.684-14.5C45.485,38.447,45.417,38.45,45.348,38.45z"
              li.vbw-text
                p
                  =t('pages.footer.handcrafted')
                  a href="http://voroninstudio.eu/" rel="nofollow"
                    =t('pages.footer.studio')
                p
                  =t('pages.footer.year')
                  /a href="http://voroninstudio.eu/" rel="nofollow" =t('pages.footer.projects_info')
              .clearfix
          .columns.large-3
            p.faw_right
              |© 2014-16 «Magia Obrus»

app/views/partials/_header.html.slim
header
  .header_wrapper
    .main_menu_wrapper.header_menu_squad
      label#main_menu_button for="main_menu" data-title=t("header.menu")
        = embedded_svg ("MO-menu.svg")
    .header_inner
      .main_logo
        a href=root_path(locale: I18n.locale)
          = embedded_svg ("MO-Logo-v2.svg")
      .main_central_block_wrap
        .mcb_one_item
          .mcb_phone
            a href="tell:+380671070727"
              .link_inner.link_phone_inner.phone-link-with-brackets
                = embedded_svg ("MO-Phone.svg"), class: "f_ico"
                span
                  |+38&nbsp;
                  .bracket
                    |(
                  |067
                  .bracket
                    |)
                  |&nbsp;107 07 27

        .mcb_one_item
          .mcb_phone
            a href="mailto:magia-obrus@ukr.net"
              .link_phone_inner
                = embedded_svg ("MO-Mail.svg")
                span
                  |magia-obrus@ukr.net
        .mcb_one_item
          .mcb_phone
            label for="call_order"
              .link_phone_inner
                = embedded_svg ("MO-Phone-call back.svg")
                .call-order-link-wrap
                  span =t("header.call_order")
            #modal_call_order
              =render partial: 'partials/forms/call_order'
      .language-switcher
        -if I18n.locale == :uk
          = link_to "EN", {locale: "en"}, title: "go to english"

          /a href="/en" EN
        -else I18n.locale == :en
          = link_to "UKR", {locale: "uk"}, title: "перейти на українську"
          /a href="/uk" UKR
    .basket_wrapper.header_menu_squad
      label#basket for="modal_cart" data-count="#{get_count_products}"
        = embedded_svg ("MO-Basket.svg")
.modal_main_menu_wrap
  .main_menu_wrap
    .row
      .columns.large-12
        .first_menu
          ul
            - subcategory = Category.where(:parent_id => true)
            li
              a.title
                span =t("category.tablecloths.title")
            li
              -if subcategory && subcategory[0]
                =link_to one_product_path(subcategory[0].category_url, locale: I18n.locale) do
                  span =t("category.tablecloths.holiday")
            li
              -if subcategory && subcategory[1]
                =link_to one_product_path(subcategory[1].category_url, locale: I18n.locale) do
                  span =t("category.tablecloths.ethno")
            li
              -if subcategory && subcategory[2]
                =link_to one_product_path(subcategory[2].category_url, locale: I18n.locale) do
                  span =t("category.tablecloths.thematic")
            li
              -if subcategory && subcategory[3]
                =link_to one_product_path(subcategory[3].category_url, locale: I18n.locale) do
                  span =t("category.tablecloths.children")
            li
              -if subcategory && subcategory[4]
                =link_to one_product_path(subcategory[4].category_url, locale: I18n.locale) do
                  span =t("category.tablecloths.branded")
            li
              a
                span =t("category.tablecloths.by_order")
        .second_menu

          ul.sm_links
            /li
            /  a href=all_sets_path
            /    |Сервізи
            li
              = link_to t("main_menu.decors"), all_decors_path(locale: I18n.locale)
            li
              a href=special_offers_path(locale: I18n.locale) =t("main_menu.promotion")
            li
              a href=all_publication_path(locale: I18n.locale) =t("main_menu.publications")
            li
              a href=shipping_path(locale: I18n.locale) =t("main_menu.delivery")
            li
              a href=warranty_path(locale: I18n.locale)  =t("main_menu.guarantee")
            li
              a href=payment_path(locale: I18n.locale) =t("main_menu.payment")
            li
              =link_to t("main_menu.contacts"), contacts_path(locale: I18n.locale)
              /a href=contacts_path =t("main_menu.contacts")
          ul.social_networks_wrap
            li
              a href="https://www.facebook.com/" rel="nofollow"
                = embedded_svg ('MO-Social-Facebook.svg')
            li
              a href="http://instagram.com/" rel="nofollow"
                = embedded_svg ('MO-Social-Instagram.svg')
            li
              a href="https://twitter.com/" rel="nofollow"
                = embedded_svg ('MO-Social-Twitter.svg')
        .clearfix
.modal_cart_wrap
  .async-partial-loader data-path="partials/forms/cart"