config/routes.rb
unless RakeSettings.self_skip_initializers?
  Rails.application.routes.draw do
    mount Ckeditor::Engine => '/ckeditor'
    devise_for :users
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

    resources :line_items
    resources :carts

    delete '/line_items/:id' => 'line_items#destroy'
    post '/customized_form' => 'main#customized_form'
    post '/call_order' => 'main#call_order'
    post '/contact_form' => 'main#contact_form'
    post '/order_product' => 'main#order_product'

    scope "(:locale)", :locale => /uk|en/ do
      get '/contacts' => 'main#contacts', as: 'contacts'

      get '/publication' => 'main#all_publication', as: 'all_publication'
      get '/publication/:url' => 'main#one_article', as: "one_article"

      get '/tablecloth' => 'product#all_tablecloth', as: 'all_tablecloth'
      get '/tablecloth/:category' => 'product#one_item', as: 'one_product'
      get '/tablecloth/:category/:name' => 'product#product_detail', as: 'product_detail'

      get '/sets' => 'product#all_sets', as: 'all_sets'
      get '/sets/:category' => 'product#sets_category', as: 'sets_category'
      get '/sets/:category/:name' => 'product#drink_set_detail', as: 'sets_detail'

      get '/decors' => 'product#all_decors', as: 'all_decors'
      get '/decors/:name' => 'product#decor_detail', as: 'decors_detail'

      get '/special_offers' => 'main#special_offers', as: 'special_offers'

      get '/delivery' => 'info#shipping', as: 'shipping'
      get '/warranty' => 'info#warranty', as: 'warranty'
      get '/payment' => 'info#payment', as: 'payment'

      get '/ordering' => 'main#ordering', as: 'ordering'

      root "main#index"

    end
    post '/add_products_pack' => 'line_items#add_product_pack_item_to_line_item', as: 'add_product_pack_item_to_line_item'
    match "*path" => redirect("/"), via: [:get, :post]
  end

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy

  def self.destroy_cart
    Cart.expired.destroy_all
    # @carts = Cart.where("updated_at < #{24.hours.ago}")
    # @carts.delete_all
  end
  scope :expired, -> { where('created_at <= ?', 24.hours.ago) }

  after_save do
    Cart.destroy_cart
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end
  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end
end

app/helpers/carts_helper.rb
module CartsHelper
  def set_cart
    @cart = Cart.find(session[:cart_id])
  rescue ActiveRecord::RecordNotFound
    @cart = Cart.create
    session[:cart_id] = @cart.id
  end
end

app/views/carts/_form.html.slim
= form_for @cart do |f|
  - if @cart.errors.any?
    #error_explanation
      h2 = "#{pluralize(@cart.errors.count, "error")} prohibited this cart from being saved:"
      ul
        - @cart.errors.full_messages.each do |message|
          li = message

  .actions = f.submit 'Save'

app/views/carts/edit.html.slim
h1 Editing cart

== render 'form'

= link_to 'Show', @cart
'|
= link_to 'Back', carts_path

app/views/carts/index.html.slim
h1 Listing carts

table
  thead
    tr
      th
      th
      th

  tbody
    - @carts.each do |cart|
      tr
        td = link_to 'Show', cart
        td = link_to 'Edit', edit_cart_path(cart)
        td = link_to 'Destroy', cart, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Cart', new_cart_path

app/views/carts/new.html.slim
h1 New cart

== render 'form'

= link_to 'Back', carts_path

app/views/carts/show_info.html.slim
.mc_inner
  -count = 0
  -rez = 0
  .mc_header
    .mch_inner
      .cart_count_product
        .count_product data-count=''
          = embedded_svg ("MO-Basket.svg")
        span
          |Ваша корзина
      label.close_cart for="modal_cart"
        =embedded_svg('MO-close button.svg')
  .cart-content-page
    .cart-content-page-inner
      -set_cart
      -cart = Cart.find(session[:cart_id])
      ul.cart_items_list
        -cart.line_items.each do |item|
          li
            -sql = "select c.* from #{Category.table_name} c, #{Product.table_name} p where p.id= '#{item.product.id}' and p.category_id = c.id"
            -category = Category.find_by_sql(sql).first
            .cart_item_image_wrap.left
              a href=product_detail_path(category.category_url, item.product.t_name, locale: I18n.locale)
                .bi style="background: url('#{item.product.image.url(:large)}')no-repeat center center;"
            .cart_item_info_wrap.left
              .row
                .columns
                  .cart_item_title
                    a href=product_detail_path(category.category_url, item.product.t_name, locale: I18n.locale)
                      h3
                        = truncate item.product.name, length: 30
              .row
                .columns.no-padding-left
                  .quantity_wrap
                    .quantity_control.quantity_minus
                      = embedded_svg('button-minus.svg')
                    input.quantity value="#{item.quantity}"
                    .quantity_control.quantity_plus
                      = embedded_svg('button-plus.svg')
                  - if item.product.product_properties[0]
                    .product_option_wrap
                      h4.product_option = item.product.product_properties[0].pp_value
            .cart_item_price_wrap.right
              .row
                .columns.no-padding-right
                  .delete-item.right data-line-item-id="#{item.id}" data-product-count=""
              .row
                .columns.no-padding-right
                  h3
                    - if item.product.promotion_price
                      = item.quantity * item.product.promotion_price
                    - else
                      = item.quantity * item.product.price
                    span
                      |&nbsp;грн
            .clearfix
          -count+=1
          - if item.product.promotion_price
            - rez+=item.product.promotion_price.round
          -else
            - rez+=item.product.price.round
    .cart_count_items data-count=count


.cart-count-prices
    .cart-count-prices-inner
      .ccp_inner.ccp_left
        |Загальна ціна
      .ccp_inner.ccp_right
        =get_total_price(current_cart)
        |&nbsp;грн
  .cart-order-product-wrap
    .cop_inner.cop-left
      .arrow
        =embedded_svg('MO-arrow.svg')
      .title
        |Продовжити покупки
    .cop_inner.cop-right.ci_next_step
      .title
        |Продовжити покупки
      .arrow
        =embedded_svg('MO-arrow.svg')