config/routes.rb
unless RakeSettings.self_skip_initializers?
  Rails.application.routes.draw do
    mount Ckeditor::Engine => '/ckeditor'
    devise_for :users
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

    resources :line_items
    resources :carts

    delete '/line_items/:id' => 'line_items#destroy'
    post '/customized_form' => 'main#customized_form'
    post '/call_order' => 'main#call_order'
    post '/contact_form' => 'main#contact_form'
    post '/order_product' => 'main#order_product'

    scope "(:locale)", :locale => /uk|en/ do
      get '/contacts' => 'main#contacts', as: 'contacts'

      get '/publication' => 'main#all_publication', as: 'all_publication'
      get '/publication/:url' => 'main#one_article', as: "one_article"

      get '/tablecloth' => 'product#all_tablecloth', as: 'all_tablecloth'
      get '/tablecloth/:category' => 'product#one_item', as: 'one_product'
      get '/tablecloth/:category/:name' => 'product#product_detail', as: 'product_detail'

      get '/sets' => 'product#all_sets', as: 'all_sets'
      get '/sets/:category' => 'product#sets_category', as: 'sets_category'
      get '/sets/:category/:name' => 'product#drink_set_detail', as: 'sets_detail'

      get '/decors' => 'product#all_decors', as: 'all_decors'
      get '/decors/:name' => 'product#decor_detail', as: 'decors_detail'

      get '/special_offers' => 'main#special_offers', as: 'special_offers'

      get '/delivery' => 'info#shipping', as: 'shipping'
      get '/warranty' => 'info#warranty', as: 'warranty'
      get '/payment' => 'info#payment', as: 'payment'

      get '/ordering' => 'main#ordering', as: 'ordering'

      root "main#index"

    end
    post '/add_products_pack' => 'line_items#add_product_pack_item_to_line_item', as: 'add_product_pack_item_to_line_item'
    match "*path" => redirect("/"), via: [:get, :post]
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :price, :short_description, :description, :image, :count_items, :category_id, :promotion_id
  attr_accessible :promotion_price
  attr_accessible :product_pack_id, :product_pack

  translates :name, :short_description, :description, :t_name, :fallbacks_for_empty_translations => true
  attr_accessible :translations
  accepts_nested_attributes_for :translations
  attr_accessible :translations_attributes

  class Translation
    attr_accessible :locale, :product_id

    attr_accessible  :name, :short_description, :description, :t_name

    rails_admin do
      visible false
      nested do
        field :locale , :hidden
        field :name do
          label 'Назва'
          help ''
        end
        field :short_description do
          label 'Короткий опис'
          help ''
        end
        field :description, :ck_editor do
          label 'Повний опис'
          help ''
        end
      end


    end
  end

  validates_presence_of :name, :message => "Заповніть це поле! Поле не може бути пустим."
  validates_presence_of :image, :message => "Виберіть фотографію, відповідно до зазначених розмірів! Поле не може бути пустим."
  validates_presence_of :short_description, :message => "Заповніть це поле! Поле не може бути пустим."
  validates_presence_of :description, :message => "Заповніть це поле! Поле не може бути пустим."

  has_attached_file :image,
                    styles: { thumb: "300x300#", large: "600x600>" },
                    convert_options: { thumb: "-quality 94 -interlace Plane",
                                       large: "-quality 94 -interlace Plane" },
                    url: "/assets/images/:class/:id/image_:style.:extension",
                    path:':rails_root/public:url'

  belongs_to :category, inverse_of: :products
  belongs_to :promotion, inverse_of: :products

  has_many :photo_galleries, as: :imageable
  attr_accessible :photo_galleries
  accepts_nested_attributes_for :photo_galleries, allow_destroy: true
  attr_accessible :photo_galleries_attributes

  has_many :product_properties, as: :characteristic
  attr_accessible :product_properties
  accepts_nested_attributes_for :product_properties, allow_destroy: true
  attr_accessible :product_properties_attributes

  belongs_to :product_pack, inverse_of: :product

  before_validation :generate_t_name
  def generate_t_name
    self.t_name = name.parameterize
  end

  # line item block begin

  has_many :line_items

  before_destroy :ensure_not_referenced_by_any_line_item

  private

  # ensure that there are no line items referencing this product
  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'Line Items present')
      return false
    end
  end

  # line item block end

  rails_admin do
    parent Category
    label 'Одиниця'
    label_plural 'Одиниці'

    list do
      field :category_id do
        label 'Категорія'
      end
      field :image do
        label 'Зображення'
      end
      field :name do
        label 'Назва'
      end
      field :t_name do
        label 'Транслітерація'
      end
      field :price do
        label 'Ціна'
      end
      field :promotion_price do
        label 'Акційна ціна'
      end
      field :count_items do
        label 'Кількість'
      end
    end

    edit do
      field :image, :paperclip do
        label 'Зображення'
        help 'Зображення для альбому повинне бути 600. / 600px.'
      end
      field :price do
        label 'Ціна'
        help ''
      end
      field :promotion_price do
        label 'Акційна ціна'
        help 'Якщо вводиться "акційна ціна, продукт буде мати іконку розпродаж.'
      end
      field :count_items do
        label 'Кількість'
        help ''
      end
      field :translations, :globalize_tabs do
        label 'Локалізації'
      end
      field :photo_galleries do
        label 'Фотогалерея'
      end
      field :product_properties do
        label 'Властивості'
      end
      field :category do
        label 'Категорія'
        help 'Виберіть категорію до якої належить товар.'
      end
      field :promotion do
        label 'Акція'
        help ''
      end
    end
  end
end

app/controllers/product_controller.rb
class ProductController < ApplicationController

  def all_tablecloth
    @tablecloth = Category.where(:parent_id => true)
  end
  def one_item
    category = params[:category]
    sql = "select p.* from #{Category.table_name} c, #{Product.table_name} p where c.category_url = '#{category}' and p.category_id = c.id"

    sql_cat = 'SELECT  "categories".* FROM "categories"  WHERE "categories"."parent_id" = 1 '
    @categories = Category.find_by_sql(sql_cat)
    @parent = Category.find_by_category_url(params[:category])
    @products = Product.find_by_sql(sql)
  end
  def product_detail
    category = params[:category]
    product = params[:name]

    @parent = Category.find_by_category_url(params[:category])

    # variant 2 for create obj product
    query = "select p.* from #{Category.table_name} c, #{Product.table_name} p where c.category_url = '#{category}' and p.t_name = '#{product}'"
    result = ActiveRecord::Base.connection.execute( query )
    @product_one_item = []
    result.each do |row|
      @product_one_item.append( Product.find( row['id'] ) )
    end
    @product = @product_one_item.first

    # create product pack object
    query2 = "select pc.* from #{ProductPack.table_name} pc, #{Product.table_name} p where p.product_pack_id = pc.id and p.id = #{@product.id}"
    result = ActiveRecord::Base.connection.execute( query2 )
    @product_pack_one_item = []
    result.each do |row|
      @product_pack_one_item.append( ProductPack.find( row['id'] ) )
    end

    @product_set = @product_pack_one_item.first
  end


  def all_sets
    @sets = DsCategory.where(:parent_id => nil)
  end

  def sets_category
    @all_category = DsCategory.where(:parent_id => nil).order('created_at DESC')
    @current_category = DsCategory.where(t_name: params[:category]).first

    category = params[:category]
    sql = "select p.* from #{DsCategory.table_name} c, #{DrinkSet.table_name} p where c.t_name = '#{category}' and p.ds_category_id = c.id"
    @products = DrinkSet.find_by_sql(sql)

  end

  def drink_set_detail
    parent_category = params[:category]
    product = params[:name]

    @parent = DsCategory.where(t_name: params[:category]).first

    query = "select p.* from #{DsCategory.table_name} c, #{DrinkSet.table_name} p where c.t_name = '#{parent_category}' and p.t_name = '#{product}'"
    result = ActiveRecord::Base.connection.execute( query )
    @product_one_item = []
    result.each do |row|
      @product_one_item.append( DrinkSet.find( row['id'] ) )
    end
    @product = @product_one_item.first

    query2 = "select pp.* from #{ProductPack.table_name} pp, #{DrinkSet.table_name} ds, set_packs sp where sp.drink_set_id = ds.id and sp.product_pack_id = pp.id and ds.id = #{@product.id}"
    result = ActiveRecord::Base.connection.execute( query2 )
    @product_pack_one_item = []
    result.each do |row|
      @product_pack_one_item.append( ProductPack.find( row['id'] ) )
    end

    @product_set = @product_pack_one_item.first

  end

  def all_decors
    # @decors = DCategory.order('created_at DESC')
    @decors = DCategory.order(created_at: :desc)
    @is_any = @decors.map{|d| d.decors.any? }.select{|v| v if v}.any?
    @is_empty = !@is_any
  end

  def decor_category
    @all_category = DCategory.order('created_at DESC')
    @current_category = DCategory.where(t_name: params[:category]).first

    category = params[:category]
    sql = "select p.* from #{DCategory.table_name} c, #{Decor.table_name} p where c.t_name = '#{category}' and p.d_category_id = c.id"
    @products = Decor.find_by_sql(sql)
  end

  def decor_detail
    # parent_category = params[:category]
    product = params[:name]

    # @parent = DCategory.find_by_t_name(params[:category])
    # query = "select p.* from #{DCategory.table_name} c, #{Decor.table_name} p where c.t_name = '#{parent_category}' and p.t_name = '#{product}'"
    # result = ActiveRecord::Base.connection.execute( query )
    # @product_one_item = []
    # result.each do |row|
    #   @product_one_item.append( Decor.find( row['id'] ) )
    # end
    # @product = @product_one_item.first

    @product = Decor.find_by_t_name(product)

    # query2 = "select pp.* from #{ProductPack.table_name} pp, #{Decor.table_name} d, decor_packs dp where dp.decor_id = d.id and dp.product_pack_id = pp.id and d.id = #{@product.id}"
    # result = ActiveRecord::Base.connection.execute( query2 )
    # @product_pack_one_item = []
    # result.each do |row|
    #   @product_pack_one_item.append( ProductPack.find( row['id'] ) )
    # end
    #
    # @product_set = @product_pack_one_item.first
  end
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/product/all_decors.html.slim
.row
  .columns.large-12
    nav class="breadcrumbs"
      a href=root_path
        = embedded_svg ('MO-Home.svg')
      a class="unavailable" href="" =t("main_menu.decors")

-if @decors
  .decors-category-wrap
    /.row
      -@decors.each_with_index do |c, index|
        .columns.large-4 class=(if @decors.last then; 'end' end;)
          .one-category-wrap
            a href=decor_category_path(c.t_name, locale: I18n.locale)
              -if c.icon.exists?
                =embedded_svg_from_root_directory "#{c.icon.path}", :class => 'svg_ico'
              h4.text-center =c.name
              .clearfix

  .product-list-wrap
    .row
      .columns.large-12
        .product-list
          .row
            -if @decors.any?
              -@decors.each do |category|
                -if category.decors.any?
                  -category.decors.each do |decor|
                    .columns.large-3.medium-4.small-6.product-block
                      .block-inner
                        .image-cont style="opacity: 1;"
                          .bi style="background: url('#{decor.image.url(:thumb)}')no-repeat center center;"
                          .product_info_wrapper
                            .pi_inner
                              a.more-info
                                .pi_top
                                  h5 =truncate decor.name, lenght: '80'
                                .pi_bottom
                                  h4
                                    =decor.price
                                    span
                                      |&nbsp;грн

                      .product-detail
                        .container
                          .row
                            .columns.large-6.medium-6
                              .bi style="background: url('#{decor.photo_galleries[0].image.url(:large)}')no-repeat center center;"
                              ul.product_gallery_images
                                -decor.photo_galleries.each_with_index do |photo, index|
                                  li
                                    a.button-for-prev href="#{photo.image.url(:large)}" class=(if index==0 then; 'active' end;)
                                      =embedded_svg('MO-picture switchers.svg')
                                    a.fancy_gallery href="#{photo.image.url(:large)}" data-fancybox-group="product_gallery_#{decor.id}" rel="product_gallery_#{decor.id}"
                            .columns.large-6.medium-6
                              .detail_info_wrap
                                .diw-title-wrap
                                  a href=decors_detail_path(decor.t_name, locale: I18n.locale)
                                    h2
                                      =decor.name
                                h3
                                  =decor.price
                                  |&nbsp;грн
                                form#form_add_to_cart
                                  .input.quantity-items-wrap
                                    a.add_one_point
                                      =embedded_svg('MO-arrow.svg')
                                    input.count_product value="1"
                                    a.remove_one_point
                                      =embedded_svg('MO-arrow.svg')
                                  .input_send.not-product-pack
                                    button.cust_button.order-product-link-wrap.is-decor data-product-id=decor.id =t("pages.product.add_to_cart")
                                  .clearfix
                                p = decor.short_description
                                a.close-detail href="#"
                                  =embedded_svg('MO-close button.svg')
                              .read-more-wrap
                                .p_read_more.read-more-items
                                  a.right href=decors_detail_path(decor.t_name, locale: I18n.locale)
                                    |Більш детально >>>
            -if @is_empty
              .columns
                p Нема жодної одиниці
            .clearfix
            /-else
              .columns
                p Нема жодної одиниці
            /.clearfix

      /ul.all_products_carousel
      /  -@decors.each_with_index do |c, index|
      /    li class=(if index==0 then; 'category_leather_tab' elsif index==1 then; 'category_wooden_tab' elsif index==2 then; 'category_d_porcelain_tab' elsif index==3 then; 'category_textile_tab'  end;)
      /      label for=(if index==0 then; 'leather_tab' elsif index==1 then; 'wooden_tab' elsif index==2 then; 'd_porcelain_tab' elsif index==3 then; 'textile_tab'  end;)
      /        -if c.icon.exists?
      /          =embedded_svg_from_root_directory "#{c.icon.path}", :class => 'svg_ico'
      /        h4 =c.name
      /

  /.row
  /  -@decors.each_with_index do |c, index|
  /    .products_tab class=(if index==0 then; 'leather_tab' elsif index==1 then; 'wooden_tab' elsif index==2 then; 'd_porcelain_tab' elsif index==3 then; 'textile_tab'  end;)
  /      -c.decors.each_with_index do |i, index|
  /        .columns.large-3.product-block
  /          .block-inner
  /            .image-cont style="opacity: 1;"
  /              .bi style="background: url('#{i.photo_galleries[0].image.url(:thumb)}')no-repeat center center;"
  /              .product_info_wrapper
  /                .pi_inner
  /                  a.more-info
  /                    .pi_top
  /                      h5 =truncate i.name, lenght: '80'
  /                    .pi_bottom
  /                      h4
  /                        =i.price
  /                        span
  /                          |&nbsp;грн
  /          .product-detail
  /            .container
  /              .row
  /                .columns.large-6
  /                  -i.photo_galleries.each_with_index do |p, index|
  /                    -if index==0
  /                      a.fancy_gallery href="#{p.image.url(:large)}" data-fancybox-group="product_gallery_#{i.id}" rel="product_gallery_#{i.id}"
  /                        .bi style="background: url('#{i.image.url(:large)}')no-repeat center center;"
  /                    -elsif index >0
  /                      a.fancy_gallery href="#{p.image.url(:large)}" data-fancybox-group="product_gallery_#{i.id}" rel="product_gallery_#{i.id}"
  /                  ul.product_gallery_images
  /                    -i.photo_galleries.each do |photo|
  /                      li
  /                        div data-image="#{photo.image.url(:large)}"
  /                          =embedded_svg('MO-picture switchers.svg')
  /                .columns.large-6
  /                  .detail_info_wrap
  /                    /a href=product_detail_path(@parent.category_url, i.t_name, locale: I18n.locale)
  /                    h2
  /                      =i.name
  /                    h3
  /                      =i.price
  /                      |&nbsp;грн
  /                    form#form_add_to_cart
  /                      .input
  /                        a.add_one_point
  /                          =embedded_svg('MO-arrow.svg')
  /                        input.count_product value="1"
  /                        a.remove_one_point
  /                          =embedded_svg('MO-arrow.svg')
  /                      .input_send
  /                        button.cust_button data-product-id=i.id
  /                          |Добавити в корзину
  /                      .clearfix
  /                    p = i.short_description
  /                    a.close-detail href="#"
  /                      =embedded_svg('MO-close button.svg')
  /
  /      .clearfix

app/views/product/all_sets.html.slim
.row
  .columns.large-12
    nav class="breadcrumbs"
      a href=root_path
        = embedded_svg ('MO-Home.svg')
      a class="unavailable" href=""
        |Сервізи

-if @sets
  .decors-category-wrap
    .row
      -@sets.each_with_index do |c, index|
        .columns.large-4 class=(if @sets.last then; 'end' end;)
          .one-category-wrap
            a href=sets_category_path(c.t_name, locale: I18n.locale)
              -if c.icon.exists?
                =embedded_svg_from_root_directory "#{c.icon.path}", :class => 'svg_ico'
              h4.text-center =c.name
              .clearfix

app/views/product/all_tablecloth.html.slim
.row
  .columns.large-12
    nav class="breadcrumbs"
      a href=root_path
        = embedded_svg ('MO-Home.svg')
      a class="unavailable" href="" =t("main_menu.tablecloths")

-if @tablecloth
  .decors-category-wrap
    .row
      -@tablecloth.each_with_index do |c, index|
        .columns.large-4 class=(if @tablecloth.last then; 'end' end;)
          .one-category-wrap
            a href=one_product_path(c.category_url, locale: I18n.locale)
              -if c.icon.exists?
                =embedded_svg_from_root_directory "#{c.icon.path}", :class => 'svg_ico'
              h4.text-center =c.name
              .clearfix
/-if @tablecloth
/  #holiday
/  #ethnic
/  #theme
/  #kids
/  #brand
/  .products_tabs_wrap
/    .row
/      .columns.large-12
/        ul.all_products_carousel
/          -@tablecloth.each_with_index do |c, index|
/            -if c.parent !=0 && index<=4
/              li class=(if index==0 then; 'category_holiday_tab' elsif index==1 then; 'category_ethnic_tab' elsif index==2 then; 'category_theme_tab' elsif index==3 then; 'category_kid_tab' elsif index==4 then; 'category_brand_tab'  end;)
/                a href=(if index==0 then; '#holiday' elsif index==1 then; '#ethnic' elsif index==2 then; '#theme' elsif index==3 then; '#kids' elsif index==4 then; '#brand'  end;)
/                  label
/                    -if c.icon.exists?
/                      =embedded_svg_from_root_directory "#{c.icon.path}", :class => 'svg_ico'
/                    h4 =c.name
/
/
/    .row
/      -@tablecloth.each_with_index do |c, index|
/        -if index<=4
/          .products_tab class=(if index==0 then; 'holiday_tab' elsif index==1 then; 'ethnic_tab' elsif index==2 then; 'theme_tab active_products_tab' elsif index==3 then; 'kid_tab' elsif index==4 then; 'brand_tab'  end;)
/            -c.products.each_with_index do |i, index|
/              .columns.large-3.product-block
/                .block-inner
/                  .image-cont style="opacity: 1;"
/                    .bi style="background: url('#{i.image.url(:thumb)}')no-repeat center center;"
/                    .product_info_wrapper
/                      .pi_inner
/                        a.more-info
/                          .pi_top
/                            h5 =truncate i.name, lenght: '80'
/                          .pi_bottom
/                            h4
/                              =i.price
/                              span
/                                |&nbsp;грн
/                .product-detail
/                  .container
/                    .row
/                      .columns.large-6
/                        -i.photo_galleries.each_with_index do |p, index|
/                          -if index==0
/                            a.fancy_gallery href="#{p.image.url(:large)}" data-fancybox-group="product_gallery_#{i.id}" rel="product_gallery_#{i.id}"
/                              .bi style="background: url('#{i.image.url(:large)}')no-repeat center center;"
/                          -elsif index >0
/                            a.fancy_gallery href="#{p.image.url(:large)}" data-fancybox-group="product_gallery_#{i.id}" rel="product_gallery_#{i.id}"
/                        ul.product_gallery_images
/                          -i.photo_galleries.each do |photo|
/                            li
/                              div data-image="#{photo.image.url(:large)}"
/                                =embedded_svg('MO-picture switchers.svg')
/                      .columns.large-6
/                        .detail_info_wrap
/                          .detail_info_inner
/                            a href=product_detail_path(c.category_url, i.t_name, locale: I18n.locale)
/                              h2
/                                =i.name
/                            h3
/                              =i.price
/                              |&nbsp;грн
/                            form#form_add_to_cart
/                              .input
/                                a.add_one_point
/                                  =embedded_svg('MO-arrow.svg')
/                                input.count_product value="1"
/                                a.remove_one_point
/                                  =embedded_svg('MO-arrow.svg')
/                              .input_send
/                                /  = button_to 'Добавити в корзину', add_product_cart_line_items_path(session[:cart], :product_id => i.id), :method => :put, :class => 'cust_button'
/                                button.cust_button data-product-id=i.id data-cart="#{session[:cart]}"
/                                  |Добавити в корзину
/                              .clearfix
/                            p = i.short_description
/                          a.close-detail
/                            =embedded_svg('MO-close button.svg')
/                        .row
/                          .columns.large-12
/                            .p_read_more.right
/                              a href=product_detail_path(c.category_url, i.t_name, locale: I18n.locale)
/                                |Більш детально >>>
/
/            .clearfix

app/views/product/decor_detail.html.slim
.row
  .columns.large-12
    nav class="breadcrumbs"
      a href=root_path
        = embedded_svg ('MO-Home.svg')
      a href=all_decors_path(locale: I18n.locale) =t("main_menu.decors")
      a class="unavailable" href=""
        =@product.name

.product_detail_wrap.one_item_product_detail_wrap
  .row
    .columns.large-12
      - if @product
        - i = @product
        .product-detail
          .container.container-item-detail
            .row
              .columns.large-6
                a.link_to_prev.fancy_gallery.fancy_gallery.item-detail-main-image data-fancybox-group="product_gallery_#{i.id}" rel="product_gallery_#{i.id}" href=i.photo_galleries[0].image.url(:large)
                  .bi style="background: url('#{i.photo_galleries[0].image.url(:large)}')no-repeat center center;"
                  .preview_ico
                    .preview_ico_inner
                      =embedded_svg('MO-Eye.svg')
                ul#product_gallery_images
                  -if i.photo_galleries.any?
                    -i.photo_galleries.each do |photo|
                      li
                        a href=photo.image.url(:large)
                          = image_tag (photo.image.url(:thumb))
                        a.fancy_gallery href="#{photo.image.url(:large)}" data-fancybox-group="product_gallery_#{i.id}" rel="product_gallery_#{i.id}"
              .columns.large-6
                .detail_info_wrap
                  h2.passive_title
                    =i.name
                  h3
                    =i.price
                    span
                      |&nbsp;грн
                  form#form_add_to_cart
                    .input.quantity-items-wrap
                      a.add_one_point
                        =embedded_svg('MO-arrow.svg')
                      input.count_product value="1"
                      a.remove_one_point
                        =embedded_svg('MO-arrow.svg')
                    .input_send.not-product-pack
                      button.cust_button.order-product-link-wrap.is-decor data-product-id=i.id =t("pages.product.add_to_cart")
                    .clearfix
                  .description_wrap
                    = raw i.description
                  -if i.product_properties && i.product_properties.count >0
                    ul.product_properties
                      -i.product_properties.each do |pp|
                        li
                          .pp_wrap.key_wrap
                            =pp.pp_key
                          .pp_wrap.value_wrap
                            =pp.pp_value

      .clearfix

/-if @product_set
/-if 1==0
  .light_gray_back_wrap.pd_products_pack_wrap
    .row
      .columns.large-12
        h4
          |Цей чайний сервіз ідеально підходить до:
    -if @product_set.drink_sets
      .row
        ul.pd_drink_sets_carousel.products_pack_item_wrap
          -p = @product_set.product
          li
            .columns.large-3
              .bi style="background: url('#{p.image.url(:thumb)}')no-repeat center center;"
            .columns.large-9
              -sql = "select c.* from #{Category.table_name} c, #{Product.table_name} p where p.id= '#{p.id}' and p.category_id = c.id"
              -category = Category.find_by_sql(sql).first
              a href=product_detail_path(category.category_url, p.t_name, locale: I18n.locale)
                h2 =p.name
              .row
                .pd_info_block
                  .columns.large-4
                    h3
                      =p.price
                      span
                        |&nbsp;грн
                  .columns.large-8
                    form#form_add_to_cart
                      .input.quantity-items-wrap
                        a.add_one_point
                          =embedded_svg('MO-arrow.svg')
                        input.count_product value="1"
                        a.remove_one_point
                          =embedded_svg('MO-arrow.svg')
                      .input_send.not-product-pack
                        button.cust_button.order-product-link-wrap.is-tablecloth data-product-id=p.id
                          |Добавити в кошик
                      .clearfix
                  .clearfix
              p = p.short_description
              .row
                .columns.large-12
                  .p_read_more.right
                    a href=product_detail_path(category.category_url, p.t_name, locale: I18n.locale)
                      |Більш детально >>>

  .pd_product_pack_wrap
    .row
      .columns.large-12
        h4
          |Разом дешевше!
        h3
          'знижка
          =@product_set.percent
          |% на комплект
        h2 =@product_set.name
    .row
      .products_pack_items_wrap data-sale="#{@product_set.percent}"
        .columns.large-3
          -prod = @product_set.product
          .bi style="background: url('#{prod.image.url(:thumb)}')no-repeat center center;" data-tablecloth-price="#{prod.price}"
        .symbol_plus_wrap
          .symbol_plus_inner
            .symbol_plus
        .columns.large-3
          .bi style="background: url('#{@product_set.drink_sets[0].photo_galleries[0].image.url(:thumb)}')no-repeat center center;" data-tablecloth-price="#{@product_set.drink_sets[0].price}"
        .symbol_plus_wrap
          .symbol_plus_inner
            .symbol_plus
        .columns.large-3
          .bi style="background: url('#{@product_set.decors[0].photo_galleries[0].image.url(:thumb)}')no-repeat center center;" data-tablecloth-price="#{@product_set.decors[0].price}"
        .clearfix
    .row
      .columns.large-12
        .row
          .columns.large-12
            .symbol_equal_wrap
              .symbol_equal_inner
                .symbol_equal
        .row
          .columns.large-12
            -tablecloth_one_item = @product_set.product.price
            -drink_set_one_item = @product_set.drink_sets[0].price
            -decor_one_item = @product_set.decors[0].price

            -percent = @product_set.percent/100.to_f
            -result = tablecloth_one_item + drink_set_one_item + decor_one_item
            -sale_result = result - result*percent
            .old_prices_result_wrap
              .old_price_result
                =result.round
                |&nbsp;грн
            .new_prices_result_wrap
              .new_price_result
                =sale_result.round
                |&nbsp;грн
        .row
          .columns.large-12
            .buy_products_pack_wrap
              .input_send
                button.cust_button.order-products-collection-link-wrap
                  |Купити комплект
              .clearfix